### PR TITLE
Support a dotlottie

### PR DESCRIPTION
**Pull request by tinyjin**
Hi, there, Thanks for this library.
However, there wasn't any support to use dotlottie.
So I just added simple code to implement it.

I know this lib is already supporting zip format which is same size with dotlottie.
But I thought It's still needed dotlottie compatible because dotlottie is more familiar than zip for lottie user.

Also, it could be improved as an independent binary so It'd be better to have dotlottie composition for then!

issue: #295 

People don't have to reformat dotlottie into zip from now on.
I already tested it with some example written by dotlottie and it worked well.

Screenshot 2023-11-03 at 1 28 41 AM

example

### CODE REVIEW

**Review by xvrh — COMMENTED** [review]
I'm not really convinced by this change.
This doesn't really bring dotlottie support. It just slightly improve the situation when there are several .json files inside an archive.

I haven't used it, but I see there is some external effort for a full-featured loader: https://pub.dev/packages/dotlottie_loader

**Comment by tinyjin** [comment]
I totally agree the features should be fully supported. This PR is for simply using dotlottie so I will check more about dotlottie spec and implement it If I can.

Thanks for review and comment. Talk to you soon!

**Comment by xvrh** [comment]
@tinyjin the next version (currently v3.0.0-alpha.1), will expose a hook to customise how to decode zip archives.
So you can choose the .json file from the archive like that:

```dart
Lottie.asset(
  'animation.lottie',
  decoder: customDecoder,
);

Future<LottieComposition?> customDecoder(List<int> bytes) {
  return LottieComposition.decodeZip(bytes, filePicker: (files) {
    return files.firstWhere((f) => f.name == 'animations/cat.json');
  });
}
```

Please, give it a try and let me know if it works for you.

**Comment by tinyjin** [comment]
Screenshot 2023-11-18 at 1 44 24 PM

@xvrh 
Thank you for sharing, yup it worked.

**Comment by tinyjin** [comment]
@xvrh 
FYI.
I checked dotlottie-loader which you mentioned and lists of full features on dotlottie.

Basically, dotlottie supports 3 new features
- Multi-animation support
- Theming support
- Interactivity

And as far as I found, dotlottie-loader supports this
- Theming support (no support)
- Interactivity (no support)
- Multi-animation support (partially works with messed code)
_- Loads animations and provide users with single animation that user can choose by selecting index of array._

Like this, In loader callback, we can drive multi animation, we can modify `animations.values.single`, `images[asset.fileName]`
```flutter
DotLottieLoader.fromAsset("assets/animation_inline_image.lottie",
        frameBuilder: (ctx, dotlottie) {
          if (dotlottie != null) {
            return Lottie.memory(dotlottie.animations.values.single,
              imageProviderFactory: (asset) {
             return MemoryImage(dotlottie.images[asset.fileName]!);
              }
            );
          } else {
            return Container();
          }
        }),
```
But not so sure It's enough interface for developer, because we have to install two different library and write messed code to load dotlottie into flutter app.


**What I'm thinking for ideal code is just like this.**
```
Lottie.asset(
  'assets/cat.lottie',
  activeAnimationId: 'cat_animation' 
),
```
It's similar with web dotlottie-player ([link](https://docs.lottiefiles.com/dotlottie-players/components/react-player/usage/using-with-multiple-animations))

The dotlottie-loader and your new interface which you just requested me to review are also cool and amazing.
Am still thinking more comfortable code base to integrate dotlottie with your lib so user just like me can load dotlottie and use multianimation with even little bit of code lines.

SO I'm going to prepare this support and request PR again however WHAT DO YOU THINK?

**Comment by tinyjin** [comment]
hello, closed issue as there's no activity =)

**Pull request closed without merging**
