### PR TITLE
Fill Performance Improvements and other fixes

### PR DESCRIPTION
**Pull request by dsyrstad**
This PR improves some fill performance issues I found with various Lottie animations. This may help with issues #30 and #98.
I think the real issue comes down to the render performance of `Path.addPath()`. I filed a Flutter issue for this: https://github.com/flutter/flutter/issues/65203. I spent a couple of weeks tracking down this issue and finding a workaround for it. The performance issue happens in the Render thread and seems directly related to how large the animation is on-screen. Flutter might be caching pre-rendered textures and running out of memory. 

I've changed how `Path.addPath()` is called and how the path is rendered for fill_content.dart and gradient_fill_content.dart. I've tested many Lottie examples, and they seem to work fine.

Just as an example, the example/assets/Tests/bm.json animation gets ~60 fps with this fix, compared to 34-52 fps with the lottie-flutter 0.6.0 release. (This is on a Pixel 3 XL)

I have an issue getting all of the tests to pass. Three of the screenshot tests currently fail:

- Screenshot AndroidWave.json at 0.0
- Screenshot Mobilo/B.json at 0.5
- Screenshot lottiefiles/atm_link.json at 1.0

They fail with the error: `Golden "golden/lottiefiles/....png": Pixel test failed, 0.00% diff detected.`. I think the "0.00% diff" is interesting. When I look at the generated test images in `test/failures/` and diff images I see no differences - specifically in the `..._isolatedDiff.png` images.

There are a couple of other changes:

- I fixed a bug with the casing of "weather" in pubspec.yaml. Without this fix, the examples don't build on Ubuntu Linux.
- The debugging class `MeanCalculator` wasn't initializing its fields, causing a null pointer exception when debugging.
- I added `antiAliasingSuggested` to `LottieDrawable` to allow fill paints to be anti-aliased. It is off by default. It also provides some minor performance improvements without any noticeable loss in quality. It is only applied to fills right now.
- I added `PathFactory` to create Paths rather than just new-ing them. path_factory.dart allows you to switch out the normal Path creation with a debug logging implementation so you can see all of the Path calls that are performed during a frame. Just create a `DebugPath` in the factory rather than `Path`.

### CODE REVIEW

**Comment by xvrh** [comment]
Hi,
Thanks for this amazing research and findings 👍 

To have the tests to pass:
- `flutter run tool/prepare_submit.dart` (to auto format all the modified files)
- `(flutter test --update-goldens test)` to update all goldens files. (You have to do this in both the root and the example folder).

While the majority of the golden files differences seems to be just noise (and can be ignored), there seems to be some important differences with gradients:
Example for "assets/lottiefiles/gradient_animated_background.json":

Before:
gradient_animated_background

After:
gradient_animated_background

Other files with gradients have similar differences (ie: the differences can be seen easily with "dynamicgradient.json" before and after your change in gradient_fill_content).

Can you have a look if we can still have a performance gain without this regression?

The other changes looks good to me 🙂. Thanks a lot.

**Comment by dsyrstad** [comment]
Thanks @xvrh. I didn't realize there were also golden tests in `example/test`. You are correct, there was an issue with gradients and I have fixed it. I've reexamined all of the golden tests and except for some "noise" differences (possible anti-aliasing and font drawing), everything looks good to me. I've updated the goldens to match, but the github checks are failing on the example tests. It could be the same kind of subtle pixel difference - it looks like github is running the checks on a mac. I'm running Ubuntu.

I was not able to run `flutter run tool/prepare_submit.dart`. I get:
```
flutter run tool/prepare_submit.dart
No supported devices connected.
The following devices were found, but are not supported by this project:
<devices are listed here...>
If you would like your app to run on android, consider running `flutter create .` to generate projects for these platforms.
```

I don't know what's going on there. I previously ran dartfmt on the repo, so I think we should be good.

**Comment by xvrh** [comment]
Hi @dsyrstad ,
> It looks like github is running the checks on a mac. I'm running Ubuntu

Yes it's hard to produce the same golden on a mac and a linux. 
I'll try to update github actions to run on a linux and add a script in the project to easily update the goldens in a docker container. So anyone will be able to produce the same goldens.

> I was not able to run flutter run tool/prepare_submit.dart

Sorry about that, the command was `flutter pub run tool/prepare_submit.dart`. Basically it runs dartfmt + a script to sort the import directives.

Thanks for the changes, I pushed the fixes directly on your branches.
Once it is green, I will merge it :-)

**Comment by dsyrstad** [comment]
Thanks @xvrh ! If you wouldn't mind giving a 👍 to https://github.com/flutter/flutter/issues/65203 it will help the Flutter team prioritize it. Hopefully we'll get a proper fix in Flutter for this issue.

**Comment by TarekkMA** [comment]
Thanks a lot for this PR it did have a significant impact on the performance of the animations.

When will this pr pushed to pub.dev?

**Comment by xvrh** [comment]
@TarekkMA great to know that it works for you.
I will try to publish it now.

**Comment by xvrh** [comment]
I published `v0.7.0` with this change :-)

**Comment by TarekkMA** [comment]
thank you

**Pull request merged**
