### PR TITLE
use FilterQuality.low to default when draw image layer to fix some image render sawtooth

### PR DESCRIPTION
**Pull request by JerryFans**
FilterQuality.none is the fastest filtering method but also the lowest quality, so use FilterQuality.low to default when draw image layer to fix some image render sawtooth by default.

### CODE REVIEW

**Comment by xvrh** [comment]
@ZanderZhan Any opinion on this? (since you were the one adding `filterQuality`)

@JerryFans Is `FilterQuality.none` not the default in Flutter for the `Image` widget? Can you expand on why it is better for lottie to default to a different setting?

**Comment by JerryFans** [comment]
Snip20220825_81
Also you can see Image widget source code. when it paint image , this FilterQuality default option is FilterQuality.low. In my flutter project use Lottie, the  image render sawtooth by default (FilterQuality.none). use FilterQuality.low to default set, can Better quality than [none]. (enum FilterQuality annotation )

**Comment by JerryFans** [comment]
> @ZanderZhan Any opinion on this? (since you were the one adding `filterQuality`)
> 
> @JerryFans Is `FilterQuality.none` not the default in Flutter for the `Image` widget? Can you expand on why it is better for lottie to default to a different setting?

Also you can see Image widget source code. when it paint image , this FilterQuality default option is FilterQuality.low.

**Comment by xvrh** [comment]
Thanks for the contribution. I released 1.4.2 with this change

**Comment by ZanderZhan** [comment]
> @ZanderZhan Any opinion on this? (since you were the one adding `filterQuality`)
> 
> @JerryFans Is `FilterQuality.none` not the default in Flutter for the `Image` widget? Can you expand on why it is better for lottie to default to a different setting?

@xvrh `FilterQuality: none` is more friendly to previous version. change to `FilterQuality.low` actually a break change and may bring an unpredictable problem to others who use older version.

**Comment by xvrh** [comment]
@ZanderZhan so you think this change is not good?

**Comment by ZanderZhan** [comment]
> @ZanderZhan so you think this change is not good?

@xvrh Yes, or maybe you should marked it an important or break change in the changelog , I think that's fine too.

**Pull request merged**
