### PR TITLE
[feat] support image layer quality setting

### PR DESCRIPTION
**Pull request by ZanderZhan**
Big image seems to be vague in low paint quality, so add the quality setting to interface.

### CODE REVIEW

**Comment by xvrh** [comment]
Thank you for the pull request.

I see in Flutter (on the `Image` widget) it is named `filterQuality`. Shouldn't we stick to this name too instead of `quality`?

Also it could be good to add the documentation of what it does exactly.

**Comment by ZanderZhan** [comment]
@xvrh I have renamed quality to filterQuality. And add the documentation. Please check it later.

**Comment by dreamer2q** [comment]
@xvrh  When can this be merged? Because, I encountered the same problem where the image quality is quite low and causes bad experience.

**Comment by xvrh** [comment]
@dreamer2q Can you checkout this PR and confirm that it solves your problem too? If so I'll merge and publish.

**Comment by dreamer2q** [comment]
> @dreamer2q Can you checkout this PR and confirm that it solves your problem too? If so I'll merge and publish.

Yes, this PR solves the problem.

But I was wondering if a lottie animation has many images to draw, how can I set each image a different `filterQuality` in order to improve performance. (This is a rare case)

**Comment by xvrh** [comment]
@dreamer2q thanks for confirming. I'll go ahead and merge this.

> how can I set each image a different filterQuality in order to improve performance.

We can imagine to use the class `LottieDelegates` for that. Something like:

```dart
Lottie.asset('animation.json',
  delegates: LottieDelegates(
    filterQuality: (image) {
      if (image == 'good.png') {
        return FilterQuality.high;
      }
      return null; // Fallback to quality configured for the widget
    }
  ),
  filterQuality: FilterQuality.low,
),
```

If you need this, you can submit a pull request 😀

**Pull request merged**
